### PR TITLE
Proton C++ binding Object Memory Management changes

### PR DESCRIPTION
**Pull request by astitcher**
This is the complete set of changes, however I can't get the amended conversion test to run without leaking a pn_connectiion_t which makes me worry!

Any help tracking that issue down would be appreciated.

### CODE REVIEW

**Comment by astitcher** [comment]
@alanconway @cliffjansen For your delectation!

**Comment by cliffjansen** [comment]
Looks excellent to me.  No sign of performance penalty.  Thumbs up, ship it, etc. etc.

**Comment by alanconway** [comment]
Ship it!

**Comment by alanconway** [comment]
Delete the conversion_test, it was testing smart pointer conversions and is no longer relevant.

connection::create should just return a connection which takes the initial refcount, get rid of owned_object in the API in my opinion.

**Comment by alanconway** [comment]
Spotted an issue: pn_data_t is _not_ reference counted so treating it as an object is incorrect. I have plans to eliminate it from the public API anyway so I think you should go ahead with this commit and I'll do my refactor after.

**Comment by alanconway** [comment]
Actually I think you can delete connection::create entirely. We always create connections via a Container or Engine which set some contexts and safely initialize connection options. We shouldn't expose access to ra pn_connection()

**Comment by astitcher** [comment]
pn_data_t certainly is refcounted. Why do you think it's not? It has _initialize _finalize methods - the whole lot! I would say that because of this proton::data should do copying explicitly rather than reuse operator=, but I didn't get that far as we are changing proton::data anyway.

I would say that proton::data is useful as an internal wrapping of pn_data_t and should be kept for this, but not be a part of the external API.

**Comment by astitcher** [comment]
I understand that conversion_test has no real use now, but it does seem to present a test case that fails - or at least I cannot understand why the code in the test is wrong so I'm puzzling over it.

I connection::create() only exists because of this test case and could be deleted if the test case is wrong - it certainly does something you don't want the use to be able to do.

**Comment by astitcher** [comment]
owned_object<> is also used for data::create() and so I think it is useful - it is clearer to my eye than using pn_data() then decref.

**Comment by alanconway** [comment]
you're right about pn_data, my mistake. Agreed about keeping it internally, I'll get it out of the public API when your changes are in. conversion_test is not a real-life test case, in real life connections are only created via engine or container so we don't need (and shouldn't expose) a raw pn_connection() via create as it hasn't had connection_options applied to it. Running the examples with valgrind should test all the realistic ways you can create a connection in the API. I think that means owned_object can also be internal-only.

**Comment by astitcher** [comment]
I think owned_object<> is also useful as an optimisation to avoid useless +1 -1 refcounting when returning objects from other factories too - Connection & Session both act as factories for Session and Link objects so I think I should use it there.

I agree conversion_test isn't real world at all, but I'm still concerned I don't understand why it leaks. It essentially points out that I don't really understand the C memory management and I don't like it!

I've spent today trying to figure out why some classes have a free that doesn't just punt to decref and I'm none the wiser. ISTM that the memory management is fatally flawed if you have free/decref and finalize, because you can't ensure that the delete processing is the same irrespective of the path that leads to it.

**Comment by astitcher** [comment]
Also I note that there is no real code that use pn_connection_free() or pn_session_free(). So I'm wondering if they should be in the external API at all.
The only places that use these are internal (ok) or tests (a little strange perhaps) and @alanconway has pn_connection_free() in engine.cpp which I think might be an error.

Another reason pn_connection_free() pn_session_free() and opn_link_free() might be internal only is that they assert that their associated endpoint has been freed on entry, so none of them can be useful as is to an API user.

**Comment by alanconway** [comment]
With the reactor, everything is created via the reactor and the reactor owns everything. If you want to keep something around you need to incref and decref when you are done.

The original proton engine API was more C-like with simple create/free function pairs. I think that is useful to maintain for C programmers but free functions should be nothing but "assert(refcount == 1); decref", I don't know why so many of them are not. 

We should clean up engine.cpp to use your refcounted connection class instead of explicit free/decref. The engine also needs to use the same connection_options as the container so there is probably an internal connection abstraction needed to set up a connection before it is presented to the user.

**Comment by astitcher** [comment]
In that case the conversion _test needs to start with a reactor - that might fix the problem (as well as rendering the entire test completely irrelevant - as you already stated)

**Comment by astitcher** [comment]
Also I'm not sure that free should be assert(refcount==1); decref; I think it should probably just be decref. As I think shared ownership is in the original engine memory model (if not then why have refcounts in the first place).

**Comment by astitcher** [comment]
So actually we should be moving to completely remove all the *_free() functions then - or at least the ones that pertain to everything that is an "object" in proton-c.

**Comment by cliffjansen** [comment]
> So actually we should be moving to completely remove all the *_free() functions then - or at
> least the ones that pertain to everything that is an "object" in proton-c.
> +1

**Comment by astitcher** [comment]
I'm going to squash this all into one change and commit it to master. The appveyor failures are the python_test failing, since this code doesn't change any code that is run during this test I think the cause is unrelated to this work.

**Comment by alanconway** [comment]
I started a new thread for discussing simplifications to the C API which is really a wider issue than this C++ discussion. Addresses some of your points above.

http://qpid.2158936.n2.nabble.com/Simplifying-proton-C-memory-management-was-Re-qpid-proton-Proton-C-binding-Object-Memory-Management--tt7634013.html

**Pull request closed without merging**
