### PR TITLE
Context

### PR DESCRIPTION
**Pull request by rhs**

### CODE REVIEW

**Comment by astitcher** [comment]
Basically, I like the look of this.
I think that the name "context" is now a liability and isn't useful to understand what the purpose here is. I think these are now "properties" of the objects to which they're attached so I'd rename this new thing to be pn_property_list_t or similar (still keeping the backwards compatible get/set_context() which becomes just the "default" property.

For my taste, for the final checkin I'd arrange the changes in the order:
- Add pn_propertylist_t interface and implementation
- Change the context objects in all the C objects
- Python wrappers

**Comment by astitcher** [comment]
I have some reservations/comments on the actual implementation here, but I'll leave that until we profile the code.

**Comment by rhs** [comment]
On Fri, Nov 21, 2014 at 1:01 PM, Andrew Stitcher notifications@github.com
wrote:

> Basically, I like the look of this.
> I think that the name "context" is now a liability and isn't useful to
> understand what the purpose here is. I think these are now "properties" of
> the objects to which they're attached so I'd rename this new thing to be
> pn_property_list_t or similar (still keeping the backwards compatible
> get/set_context() which becomes just the "default" property.
> 
> It's a list in implementation only, and I hate compound noun phrases,
> particularly given how awkward they are with our naming convention. I could
> probably live with pn_properties_t although given the potential for
> confusion/overlap with AMQP's use of the term property, I think
> pn_context_t might be a better choice.

When you say it is a liability, are you thinking with respect to existing
users and the fact that it is redefining/expanding the notion of what
"context" is, or do you think it would be problematic for a new user coming
to things fresh?

> For my taste, for the final checkin I'd arrange the changes in the order:
> - Add pn_propertylist_t interface and implementation
> - Change the context objects in all the C objects
> - Python wrappers
> 
> I think it should split up this way fairly easy. At the very least the
> python wrappers will definitely be a distinct chunk of work. For the first
> two I'll certainly give it a shot, but no promises if it involves too much
> rework. ;-)

--Rafael

**Comment by astitcher** [comment]
On 11/21/2014 01:46 PM, Rafael Schloming wrote:

> It's a list in implementation only,
> I just checked with my non-technical consultant and "list" is the
> correct word to describe what we have here. The word only implies that
> there is more than one property (think of association list).
> ... I could
> probably live with pn_properties_t although given the potential for
> confusion/overlap with AMQP's use of the term property, I think
> pn_context_t might be a better choice.
> I would be happy with pn_properties_t.

I agree that there is a potential confusion with AMQP properties, but I
can't think of a better word.

"context" just does not describe what is going on here. You attach a
"named" "property" to an object; the fact that the thing you attach is
"context" from the pov of the thing doing the attaching is not relevant
to the API anymore IMO.

> When you say it is a liability, are you thinking with respect to existing
> users and the fact that it is redefining/expanding the notion of what
> "context" is, or do you think it would be problematic for a new user
> coming
> to things fresh?
> I think that the name "context" is unhelpful to tell you what it's for,
> and now that we have a new thing it's time to use a more understandable
> terminology.
> 
> > For my taste, for the final checkin I'd arrange the changes in the
> > order:
> > - Add pn_propertylist_t interface and implementation
> > - Change the context objects in all the C objects
> > - Python wrappers
> > 
> > I think it should split up this way fairly easy. At the very least the
> > python wrappers will definitely be a distinct chunk of work. For the first
> > two I'll certainly give it a shot, but no promises if it involves too much
> > rework. ;-)

Sure, making a single combined change wouldn't be terrible.

**Comment by rhs** [comment]
On Fri, Nov 21, 2014 at 2:11 PM, Andrew Stitcher notifications@github.com
wrote:

> On 11/21/2014 01:46 PM, Rafael Schloming wrote:
> 
> > It's a list in implementation only,
> > I just checked with my non-technical consultant and "list" is the
> > correct word to describe what we have here. The word only implies that
> > there is more than one property (think of association list).
> > ... I could
> > probably live with pn_properties_t although given the potential for
> > confusion/overlap with AMQP's use of the term property, I think
> > pn_context_t might be a better choice.
> > I would be happy with pn_properties_t.
> 
> I agree that there is a potential confusion with AMQP properties, but I
> can't think of a better word.

I made an attempt to rename context -> properties, but unfortunately I
discovered some actual conflicts. Currently pn_connection_properties,
pn_session_properties, etc, all exist and return a pn_data_t for accessing
what the spec refers to as connection properties, session properties, etc.

--Rafael

**Comment by astitcher** [comment]
How annoying, reaches for thesaurus...
no nothing useful.
Hmmm

**Comment by astitcher** [comment]
how about attribute?

**Comment by astitcher** [comment]
or feature, or aspect, note, facet
(all from the thesaurus when I found the right section)

**Comment by rhs** [comment]
Hopefully that should work. I'll give it a shot and see if I run into any
annoying conflicts.

**Comment by astitcher** [comment]
This has already gone to the main apache repo

**Pull request closed without merging**
